[package]
name = "rocksdb-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = { version = "0.23.0", features = ["multi-threaded-cf"] }
anyhow = "1.0.91"
serde = { version = "1.0.213", features = ["derive"] }
postcard = "1.0.10"
tracing = "0.1.40"
bellscoin = "0.30.8"
dutils = "0.1.12"
num_cpus = "1.16.0"
